apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    purpose: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
      labels:
        app: cart
    spec:
      tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "roboshop"
          effect: "PreferNoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cart
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: cart
          image: 826334059644.dkr.ecr.us-east-1.amazonaws.com/roboshop-cart-int:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 200Mi
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: CATALOGUE_HOST
              value: "catalogue"
            - name: CATALOGUE_PORT
              value: "8080"

